# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='username',
            new_name='user',
        ),
    ]
