# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20170307_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
