# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20170330_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(unique=True, verbose_name='scheduled time'),
        ),
    ]
